import { type Locale, i18n } from "@/i18n-config"
import { cn } from "@cohost/ui/lib/utils"
import "@cohost/ui/styles.css"
import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "../globals.css"
import Header from "@/app/components/header"
import { ThemeProvider } from "@/app/theme-provider"

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }))
}

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans"
})

export const metadata: Metadata = {
	title: "Builder",
	description: "Generated by create next app"
}

export default function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode
	params: { lang: Locale }
}>) {
	return (
		<html lang={params.lang} suppressHydrationWarning>
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<Header lang={params.lang} />
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
